/**
 * Dentales Liberato - Catálogo de permisos del sistema
 * Cada permiso se asigna a roles vía tabla rol_permisos
 */
export const PERMISOS = {
  INVENTARIO_VER: 'inventario.ver',
  INVENTARIO_VER_COSTOS: 'inventario.ver_costos',
  PRODUCTOS_CREAR: 'productos.crear',
  PRODUCTOS_EDITAR: 'productos.editar',
  PRODUCTOS_ELIMINAR: 'productos.eliminar',
  PRODUCTOS_EDITAR_PRECIO: 'productos.editar_precio',
  MOVIMIENTOS_VER: 'movimientos.ver',
  MOVIMIENTOS_ENTRADA: 'movimientos.entrada',
  MOVIMIENTOS_SALIDA: 'movimientos.salida',
  MOVIMIENTOS_AJUSTE: 'movimientos.ajuste',
  CATEGORIAS_VER: 'categorias.ver',
  CATEGORIAS_GESTIONAR: 'categorias.gestionar',
  USUARIOS_VER: 'usuarios.ver',
  USUARIOS_GESTIONAR: 'usuarios.gestionar',
  ROLES_VER: 'roles.ver',
  ROLES_GESTIONAR: 'roles.gestionar',
  REPORTES_VER: 'reportes.ver',
  REPORTES_EXPORTAR: 'reportes.exportar',
  SOLICITUDES_CREAR: 'solicitudes.crear',
  SOLICITUDES_GESTIONAR: 'solicitudes.gestionar',
  ALERTAS_VER: 'alertas.ver',
  PROVEEDORES_GESTIONAR: 'proveedores.gestionar',
  DASHBOARD_VER_COSTOS: 'dashboard.ver_costos',
  KARDEX_VER: 'kardex.ver',
  CONTEOS_VER: 'conteos.ver',
  CONTEOS_GESTIONAR: 'conteos.gestionar',
  ORDENES_VER: 'ordenes.ver',
  ORDENES_GESTIONAR: 'ordenes.gestionar',
  PROVEEDORES_VER: 'proveedores.ver',
  AUDITORIA_VER: 'auditoria.ver',
  PERFIL_EDITAR: 'perfil.editar',
  // Nuevos permisos ERP
  PACIENTES_VER: 'pacientes.ver',
  PACIENTES_GESTIONAR: 'pacientes.gestionar',
  CASOS_VER: 'casos.ver',
  CASOS_CREAR: 'casos.crear',
  CASOS_EDITAR: 'casos.editar',
  CASOS_ELIMINAR: 'casos.eliminar',
  CASOS_COMPLETAR: 'casos.completar',
  CASOS_MATERIALES: 'casos.materiales',
  FINANZAS_VER: 'finanzas.ver',
  FINANZAS_RESUMEN: 'finanzas.resumen',
  FINANZAS_TRANSACCIONES: 'finanzas.transacciones',
  FINANZAS_CREAR_TRANSACCION: 'finanzas.crear_transaccion',
  ABONOS_VER: 'abonos.ver',
  ABONOS_CREAR: 'abonos.crear',
  ABONOS_ELIMINAR: 'abonos.eliminar',
  CUENTAS_VER: 'cuentas.ver',
  CUENTAS_GESTIONAR: 'cuentas.gestionar',
  CAJA_VER: 'caja.ver',
  CAJA_MOVIMIENTOS: 'caja.movimientos',
} as const;

export type PermisoCodigo = (typeof PERMISOS)[keyof typeof PERMISOS];

export const TODOS_PERMISOS: { codigo: PermisoCodigo; nombre: string; modulo: string; descripcion: string }[] = [
  { codigo: PERMISOS.INVENTARIO_VER, nombre: 'Ver inventario', modulo: 'inventario', descripcion: 'Consultar productos y stock' },
  { codigo: PERMISOS.INVENTARIO_VER_COSTOS, nombre: 'Ver costos', modulo: 'inventario', descripcion: 'Ver precios y valor en bodega' },
  { codigo: PERMISOS.PRODUCTOS_CREAR, nombre: 'Crear productos', modulo: 'productos', descripcion: 'Registrar nuevos insumos' },
  { codigo: PERMISOS.PRODUCTOS_EDITAR, nombre: 'Editar productos', modulo: 'productos', descripcion: 'Modificar datos de productos' },
  { codigo: PERMISOS.PRODUCTOS_ELIMINAR, nombre: 'Eliminar productos', modulo: 'productos', descripcion: 'Desactivar productos' },
  { codigo: PERMISOS.PRODUCTOS_EDITAR_PRECIO, nombre: 'Editar precios', modulo: 'productos', descripcion: 'Modificar precio unitario' },
  { codigo: PERMISOS.MOVIMIENTOS_VER, nombre: 'Ver movimientos', modulo: 'movimientos', descripcion: 'Historial y kardex' },
  { codigo: PERMISOS.MOVIMIENTOS_ENTRADA, nombre: 'Registrar entradas', modulo: 'movimientos', descripcion: 'Compras y recepciones' },
  { codigo: PERMISOS.MOVIMIENTOS_SALIDA, nombre: 'Registrar salidas', modulo: 'movimientos', descripcion: 'Consumo clínico' },
  { codigo: PERMISOS.MOVIMIENTOS_AJUSTE, nombre: 'Ajustes de inventario', modulo: 'movimientos', descripcion: 'Correcciones de stock' },
  { codigo: PERMISOS.CATEGORIAS_VER, nombre: 'Ver categorías', modulo: 'categorias', descripcion: 'Listar categorías' },
  { codigo: PERMISOS.CATEGORIAS_GESTIONAR, nombre: 'Gestionar categorías', modulo: 'categorias', descripcion: 'CRUD categorías' },
  { codigo: PERMISOS.USUARIOS_VER, nombre: 'Ver usuarios', modulo: 'usuarios', descripcion: 'Listar personal' },
  { codigo: PERMISOS.USUARIOS_GESTIONAR, nombre: 'Gestionar usuarios', modulo: 'usuarios', descripcion: 'CRUD usuarios y asignar roles' },
  { codigo: PERMISOS.ROLES_VER, nombre: 'Ver roles', modulo: 'roles', descripcion: 'Consultar roles' },
  { codigo: PERMISOS.ROLES_GESTIONAR, nombre: 'Gestionar roles', modulo: 'roles', descripcion: 'Asignar permisos a roles' },
  { codigo: PERMISOS.REPORTES_VER, nombre: 'Ver reportes', modulo: 'reportes', descripcion: 'Panel de reportes' },
  { codigo: PERMISOS.REPORTES_EXPORTAR, nombre: 'Exportar reportes', modulo: 'reportes', descripcion: 'CSV/Excel' },
  { codigo: PERMISOS.SOLICITUDES_CREAR, nombre: 'Crear solicitudes', modulo: 'solicitudes', descripcion: 'Pedir reposición de stock' },
  { codigo: PERMISOS.SOLICITUDES_GESTIONAR, nombre: 'Gestionar solicitudes', modulo: 'solicitudes', descripcion: 'Aprobar o rechazar pedidos' },
  { codigo: PERMISOS.ALERTAS_VER, nombre: 'Ver alertas', modulo: 'alertas', descripcion: 'Stock bajo y vencimientos' },
  { codigo: PERMISOS.PROVEEDORES_GESTIONAR, nombre: 'Gestionar proveedores', modulo: 'proveedores', descripcion: 'CRUD proveedores' },
  { codigo: PERMISOS.DASHBOARD_VER_COSTOS, nombre: 'Dashboard costos', modulo: 'dashboard', descripcion: 'Valor total en bodega' },
  { codigo: PERMISOS.KARDEX_VER, nombre: 'Ver kardex', modulo: 'movimientos', descripcion: 'Historial por producto' },
  { codigo: PERMISOS.CONTEOS_VER, nombre: 'Ver conteos', modulo: 'conteos', descripcion: 'Toma física de inventario' },
  { codigo: PERMISOS.CONTEOS_GESTIONAR, nombre: 'Gestionar conteos', modulo: 'conteos', descripcion: 'Crear y cerrar conteos' },
  { codigo: PERMISOS.ORDENES_VER, nombre: 'Ver órdenes de compra', modulo: 'ordenes', descripcion: 'Consultar pedidos a proveedores' },
  { codigo: PERMISOS.ORDENES_GESTIONAR, nombre: 'Gestionar órdenes', modulo: 'ordenes', descripcion: 'Crear y recibir órdenes' },
  { codigo: PERMISOS.PROVEEDORES_VER, nombre: 'Ver proveedores', modulo: 'proveedores', descripcion: 'Listar proveedores' },
  { codigo: PERMISOS.AUDITORIA_VER, nombre: 'Ver auditoría', modulo: 'auditoria', descripcion: 'Log de acciones del sistema' },
  { codigo: PERMISOS.PERFIL_EDITAR, nombre: 'Editar perfil', modulo: 'perfil', descripcion: 'Cambiar contraseña y datos' },
  { codigo: PERMISOS.PACIENTES_VER, nombre: 'Ver pacientes', modulo: 'pacientes', descripcion: 'Listar pacientes del laboratorio' },
  { codigo: PERMISOS.PACIENTES_GESTIONAR, nombre: 'Gestionar pacientes', modulo: 'pacientes', descripcion: 'CRUD de pacientes' },
  { codigo: PERMISOS.CASOS_VER, nombre: 'Ver casos', modulo: 'casos', descripcion: 'Listar trabajos dentales' },
  { codigo: PERMISOS.CASOS_CREAR, nombre: 'Crear casos', modulo: 'casos', descripcion: 'Registrar nuevos trabajos' },
  { codigo: PERMISOS.CASOS_EDITAR, nombre: 'Editar casos', modulo: 'casos', descripcion: 'Modificar datos de casos' },
  { codigo: PERMISOS.CASOS_ELIMINAR, nombre: 'Eliminar casos', modulo: 'casos', descripcion: 'Eliminar trabajos' },
  { codigo: PERMISOS.CASOS_COMPLETAR, nombre: 'Completar casos', modulo: 'casos', descripcion: 'Marcar casos como completados' },
  { codigo: PERMISOS.CASOS_MATERIALES, nombre: 'Gestionar materiales de casos', modulo: 'casos', descripcion: 'Agregar/eliminar materiales a casos' },
  { codigo: PERMISOS.FINANZAS_VER, nombre: 'Ver finanzas', modulo: 'finanzas', descripcion: 'Acceso al módulo financiero' },
  { codigo: PERMISOS.FINANZAS_RESUMEN, nombre: 'Ver resumen financiero', modulo: 'finanzas', descripcion: 'Ver métricas financieras' },
  { codigo: PERMISOS.FINANZAS_TRANSACCIONES, nombre: 'Ver transacciones', modulo: 'finanzas', descripcion: 'Historial de movimientos' },
  { codigo: PERMISOS.FINANZAS_CREAR_TRANSACCION, nombre: 'Crear transacciones', modulo: 'finanzas', descripcion: 'Registrar ingresos y gastos' },
  { codigo: PERMISOS.ABONOS_VER, nombre: 'Ver abonos', modulo: 'abonos', descripcion: 'Historial de abonos' },
  { codigo: PERMISOS.ABONOS_CREAR, nombre: 'Crear abonos', modulo: 'abonos', descripcion: 'Registrar pagos' },
  { codigo: PERMISOS.ABONOS_ELIMINAR, nombre: 'Eliminar abonos', modulo: 'abonos', descripcion: 'Anular pagos' },
  { codigo: PERMISOS.CUENTAS_VER, nombre: 'Ver cuentas', modulo: 'cuentas', descripcion: 'Ver cuentas por cobrar/pagar' },
  { codigo: PERMISOS.CUENTAS_GESTIONAR, nombre: 'Gestionar cuentas', modulo: 'cuentas', descripcion: 'Administrar cuentas' },
  { codigo: PERMISOS.CAJA_VER, nombre: 'Ver caja', modulo: 'caja', descripcion: 'Ver saldo de caja' },
  { codigo: PERMISOS.CAJA_MOVIMIENTOS, nombre: 'Ver movimientos de caja', modulo: 'caja', descripcion: 'Historial de caja' },
];

/** Permisos del rol técnico dental */
export const PERMISOS_TECNICO: PermisoCodigo[] = [
  PERMISOS.INVENTARIO_VER,
  PERMISOS.MOVIMIENTOS_VER,
  PERMISOS.MOVIMIENTOS_SALIDA,
  PERMISOS.CATEGORIAS_VER,
  PERMISOS.SOLICITUDES_CREAR,
  PERMISOS.ALERTAS_VER,
  PERMISOS.REPORTES_VER,
  PERMISOS.KARDEX_VER,
  PERMISOS.CONTEOS_VER,
  PERMISOS.ORDENES_VER,
  PERMISOS.PROVEEDORES_VER,
  PERMISOS.PERFIL_EDITAR,
  // Nuevos permisos ERP para técnico
  PERMISOS.PACIENTES_VER,
  PERMISOS.CASOS_VER,
  PERMISOS.CASOS_MATERIALES,
  PERMISOS.FINANZAS_VER,
  PERMISOS.ABONOS_VER,
  PERMISOS.CUENTAS_VER,
  PERMISOS.CAJA_VER,
];

export function tienePermiso(permisos: string[], codigo: string): boolean {
  return permisos.includes(codigo);
}
